In [1]:
import numpy as np
import sympy as sp

In [53]:
x=np.array([[0,1],[1,0]])
y=np.array([[0,-1j],[1j,0]])
z=np.array([[1,0],[0,-1]])
def conmutador(a,b):
    c=a@b-b@a
    return c

In [54]:
#Codigo para saber si la permutacion de i,j,k es par o impar extraido de: https://python-forum.io/thread-11603.html
def is_even(p):
  i = 0
  count = 0
  while(i < len(p)):
    k = i + 1
    while(k < len(p)):
      if(p[i] > p[k]):
        count+=1
      k+=1
    i+=1
  if(count == 0):
    return True
  if(count % 2 == 0):
    return True
  else:
    return False


In [61]:
def comprobacion(x,i,j,k):
    e=1
    p=np.array([i,j,k])
    if is_even(p)==True:
        e=1
    if is_even(p)==False:
        e=-1
    if i==j or j==k or k==i:
        e=0
    r=2j*e*x
    return r

In [62]:
conmutador(x,y),conmutador(y,z),conmutador(z,x)


(array([[0.+2.j, 0.+0.j],
        [0.+0.j, 0.-2.j]]),
 array([[0.+0.j, 0.+2.j],
        [0.+2.j, 0.+0.j]]),
 array([[ 0,  2],
        [-2,  0]]))

In [63]:
comprobacion(z,1,2,3), comprobacion(x,2,3,1), comprobacion(y,3,1,2)


(array([[ 0.+2.j,  0.+0.j],
        [ 0.+0.j, -0.-2.j]]),
 array([[0.+0.j, 0.+2.j],
        [0.+2.j, 0.+0.j]]),
 array([[ 0.+0.j,  2.-0.j],
        [-2.+0.j,  0.+0.j]]))

In [64]:
conmutador(x,x)

array([[0, 0],
       [0, 0]])

In [66]:
comprobacion(z,1,1,3)

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j]])