In [1]:
import numpy as np

In [16]:
A=np.array([[4,1,1],[1,3,2],[1,2,5]])
A
def rot (A, m=100,tol=1e-10):
    theta=0
    R=np.array([[np.cos(theta),-np.sin(theta),0],[np.sin(theta),np.cos(theta),0],[0,0,1]])
    Rt=np.linalg.inv(R)
    D=np.zeros_like(Rt@A@R)
    k=0
    l=0
    maxvalue=0
    for i in range(m):
        for p in range(3):
            for q in range(p+1,3):
                if abs(A[p,q]) > maxvalue:
                    maxvalue = abs(A[p,q])
                    k = p
                    l = q
        if A[k,k] == A[l,l]:
            theta = np.pi / 4
        
        else:
            t = (-2 * A[k,l]) / (A[k,k] - A[l,l])
            theta = np.arctan(t)*(1/2)
     
        D = np.dot(np.dot(R.T, A), R)
        off_diag = np.sum(np.abs(D - np.diag(np.diag(D))))
        if off_diag < tol:
            break

    return np.diag(D)
rot(A)

array([4., 3., 5.])

In [3]:
np.linalg.eig(A)

(array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))