In [48]:
import numpy as np

In [49]:
LisF=[lambda v: 6*v[0]-2*np.cos(v[1]*v[2])-1,
      lambda v: 9*v[1]+np.sqrt(v[0]**2+np.sin(v[2])+1.06)+0.9,
      lambda v: 60*v[2]+3*np.e**(-v[0]*v[1])+10*np.pi-3]

In [50]:
def JacobianoO4(LisF,h,x):
    if len(LisF)!=len(x):
        return "La cantidad de funciones no es igual a la de incognitas"
    
    N=len(x)
    J=np.zeros([N,N])
    
    for i in range(len(LisF)):
        for j in range(len(x)):
            J[i][j]=DerivadaO4Vi(LisF[i],h,x,j)
    
    return J

In [51]:
def DerivadaO4Vi(F,h,v,i):
    v2=np.zeros(len(v))
    v2[i]=v2[i]+2*h
    v2=v+v2
    
    v1=np.zeros(len(v))
    v1[i]=v1[i]+h
    v1=v+v1

    vm1=np.zeros(len(v))
    vm1[i]=vm1[i]-h
    vm1=v+vm1

    vm2=np.zeros(len(v))
    vm2[i]=vm2[i]-2*h
    vm2=v+vm2
    
    res=(-F(v2)+8*F(v1)-8*F(vm1)+F(vm2))/(12*h)
    return res

def DerivadaO2Vi(F,h,v,i):
    v1=np.zeros(len(v))
    v1[i]=v1[i]+h
    v1=v+v1
    
    vm1=np.zeros(len(v))
    vm1[i]=vm1[i]-h
    vm1=v+vm1
    
    res=(F(v1)-F(vm1))/(2*h)
    return res

In [52]:
O4=JacobianoO4(LisF,0.01,[0.5,0.5,0.5])
print(Res1)

[[ 6.          0.24740396  0.24740396]
 [ 0.37377753  9.          0.32802064]
 [-1.16820117 -1.16820117 60.        ]]


In [53]:
def JacobianoO2(LisF,h,x):
    if len(LisF)!=len(x):
        return "La cantidad de funciones no es igual a la de incognitas"
    
    N=len(x)
    J=np.zeros([N,N])
    
    for i in range(len(LisF)):
        for j in range(len(x)):
            J[i][j]=DerivadaO2Vi(LisF[i],h,x,j)
    
    return J

In [54]:
Mismoh=JacobianoO2(LisF,0.01,[0.5,0.5,0.5])
print(a)

[[ 6.          0.24740293  0.24740293]
 [ 0.37376854  9.          0.32801836]
 [-1.16820604 -1.16820604 60.        ]]


In [55]:
print(0.01**4)
print(0.01**2)
print(0.0001**2)

1e-08
0.0001
1e-08


In [56]:
##Creo que tendrán la misma presición si h=0.0001 en el O(h^2)

In [60]:
Ajustadoh=JacobianoO2(LisF,0.0001,[0.5,0.5,0.5])

In [61]:
print(O4/Mismoh)
print(O4/Ajustadoh)

[[1.         1.00000417 1.00000417]
 [1.00002404 1.         1.00000696]
 [0.99999583 0.99999583 1.        ]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [62]:
##La división demuestra que al ajustar h se obtiene practicamente los mismos numeros